.TH "RIP RIP HOORAY!" "1" "September 2023" "Rip Rip Hooray! v0.0.2" "User Commands"
.SH NAME
Rip Rip Hooray! \- Manual page for riprip v0.0.2.
.SH DESCRIPTION
An incremental, second\-stage audio CD ripper for advanced data recovery.
.SS USAGE:
.TP
riprip [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-\-clean\fR
Clear the contents of $PWD/_riprip before doing anything else, to e.g. start over from scratch.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-no\-c2\fR
Disable/ignore C2 error pointer information when ripping, e.g. for drives that do not support the feature. (This flag is otherwise not recommended.)
.TP
\fB\-\-no\-rip\fR
Just print the basic disc information to STDERR and exit.
.TP
\fB\-\-raw\fR
Save ripped tracks in raw PCM format (instead of WAV).
.TP
\fB\-\-reconfirm\fR
Reset the status of all previously\-accepted samples to require reconfirmation. This has no effect when the paranoia level is less than 2.
.TP
\fB\-\-reconfirm\fR
Reset the status of all previously\-accepted samples to require reconfirmation. This has no effect when the paranoia level is less than 2.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-d\fR, \fB\-\-dev\fR <PATH>
The device path for the optical drive containing the CD of interest, like /dev/cdrom. [default: auto]
.TP
\fB\-o\fR, \fB\-\-offset\fR <SAMPLES>
The AccurateRip, et al, sample read offset to apply to data retrieved from the drive. [default: auto or 0; range: ±5880]
.TP
\fB\-\-paranoia\fR <NUM>
When C2 or read errors are reported for any samples in a given block, treat the rest of its samples — the ones that were allegedly good — as suspicious until they have been confirmed <NUM> times. Similarly, if a sample moves from bad to good, require <NUM> confirmations before believing it. [default: 3; range: 1..=32]
.TP
\fB\-\-refine\fR <NUM>
Execute up to <NUM> additional rip passes for each track while any samples remain unread/unconfirmed. [default: 0; max: 15]
.TP
\fB\-t\fR, \fB\-\-track\fR <NUM>
Rip one or more specific tracks (rather than the whole disc). Multiple tracks can be separated by commas (2,3), specified as an inclusive range (2\-3), and/or given their own \-t/\-\-track (\-t 2 \-t 3). [default: the whole disc]
