[package]
name = "riprip_core"
version = "0.2.8"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
description = "The library for Rip Rip Hooray."
repository = "https://github.com/Blobfolio/riprip"
readme = "README.md"
publish = false

[dependencies]
cdtoc = "0.5.*"
crc32fast = "=1.4.2"
dactyl = "0.7.*"
tempfile = "3.8.0"
trimothy = "0.3.*"
utc2k = "0.9.*"

[dependencies.argyle]
version = "0.8.*"
optional = true

[dependencies.fyi_msg]
version = "0.14.*"
features = [ "progress" ]

[dependencies.libcdio-sys]
version = "=0.5.1"
default-features = false
features = [ "cdio" ]

[dependencies.minreq]
version = "2.12.*"
default-features = false
# Neither AccurateRip nor CTDB use SSL for whatever
# reason so we don't need any minreq features at all!

[build-dependencies.cdtoc]
version = "0.5.*"
default-features = false
features = [ "accuraterip" ]

[build-dependencies.minreq]
version = "2.12.*"
default-features = false

[dev-dependencies]
fastrand = "2"

[features]
default = []

# This feature adds a few generic RipRipError types for the binary.
# It is not something external crates need to worry about.
bin = [ "argyle" ]
