[package]
name = "riprip_core"
version = "0.7.0"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2024"
description = "The library for Rip Rip Hooray."
repository = "https://github.com/Blobfolio/riprip"
readme = "README.md"
publish = false

[dependencies]
cdtoc = "0.14.*"
crc32fast = "1.5.*"
dactyl = "0.13.*"
tempfile = "3.8.0"
trimothy = "0.9.*"
utc2k = "0.21.*"
crc = "3.4.0"
encoding_rs = "0.8.35"

[dependencies.fyi_msg]
version = "2.7.*"
features = [ "signals" ]

[dependencies.libcdio-sys]
version = "=3.0.0"
default-features = false
optional = true

[dependencies.rusb]
version = "0.9.4"
optional = true

[dependencies.nix]
version = "0.31.3"
features = ["user"]
optional = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-io-kit = { version = "0.3.2", optional = true }
objc2-core-foundation = { version = "0.3.2", optional = true, features = [ "CFBase", "CFDictionary", "CFNumber", "CFString" ] }

[dependencies.minreq]
version = "3.0.*"
default-features = false
features = [ "https" ]

[dependencies.oxford_join]
version = "0.7.*"
optional = true

[build-dependencies]
dactyl = "0.13.*"
oxford_join = "0.7.*"

[build-dependencies.cdtoc]
version = "0.14.*"
default-features = false
features = [ "accuraterip" ]

[dev-dependencies]
fastrand = "2"

[features]
default = []

# This feature adds a few generic RipRipError types for the binary.
# It is not something external crates need to worry about.
bin = [ "oxford_join" ]

# Use libcdio driver. (Currently required.)
libcdio = [ "libcdio-sys" ]

# Build and link libcdio statically.
libcdio-static = [ "libcdio", "libcdio-sys/vendored" ]

libusb = [
    "rusb",
    "nix",
    "objc2-io-kit",
    "objc2-core-foundation",
]
