[package]
name = "riprip_core"
version = "0.0.7"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.70"
description = "The library for Rip Rip Hooray."
repository = "https://github.com/Blobfolio/riprip"
readme = "README.md"
publish = false

[dependencies]
bincode = "1.3.3"
crc32fast = "1.3.2"
dactyl = "0.5.*"
hound = "3.5.0"
tempfile = "3.8.0"
trimothy = "0.1.*"

[dependencies.argyle]
version = "0.6.*"
optional = true

[dependencies.cdtoc]
version = "0.2.*"
features = [ "serde" ]

[dependencies.fyi_msg]
version = "0.11.*"
features = [ "progress" ]

[dependencies.libcdio-sys]
version = "=0.5.0"
default-features = false
features = [ "cdio" ]

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[dependencies.ureq]
version = "2.7.0"
default-features = false
# Neither AccurateRip nor CTDB use SSL for whatever
# reason so we don't need any ureq features at all.

[dependencies.zstd]
version="0.12.*"
default-features=false
features = [ "zstdmt" ]

[build-dependencies.ureq]
version = "2.7.0"
default-features = false

[features]
default = []

# This feature adds a few generic RipRipError types for the binary.
# It is not something external crates need to worry about.
bin = [ "argyle" ]
